/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/AirFlow.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/AirFlow.glb [19.49MB] > AirFlow-transformed.glb [3.9MB] (80%)
*/

import { useGLTF } from '@react-three/drei'

export function Laminar(props) {
  const { nodes, materials } = useGLTF('models/AirFlow-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Glass_laminar_front.geometry} material={materials['laminar glass']} position={[0, 1.286, 0.443]} />
      <mesh castShadow receiveShadow geometry={nodes.Hexa_holes.geometry} material={materials['iron brushed']} position={[-0.915, 1.62, -0.297]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.Laminar.geometry} material={materials['Sandblasted 4k aluminium laminar']} position={[0, 1.5, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Stand_laminar.geometry} material={materials['Sandblasted 4k aluminium']} position={[0.001, 0.157, -0.005]} />
      <mesh castShadow receiveShadow geometry={nodes.Text.geometry} material={materials['Biobase text']} position={[-0.845, 1.97, 0.503]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/AirFlow-transformed.glb')
