/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/Asset_lab_industri.glb --transform --shadows --keepgroups 
Files: /home/TA/resource/Laboratory/Asset_lab_industri.glb [42.57MB] > Asset_lab_industri-transformed.glb [4.73MB] (89%)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { RigidBody } from '@react-three/rapier'

export function LabIndustri(props) {
  const { nodes, materials } = useGLTF('models/Asset_lab_industri-transformed.glb')
  useFrame(() => {
    // 
  }, 17)
  return (
    <group {...props} dispose={null}>
      <group>
        <RigidBody colliders='cuboid' type='fixed' position={[18.092, 5, -30.822]} rotation={[Math.PI, 0, Math.PI]}>
          <group>
            <mesh castShadow receiveShadow geometry={nodes.Kostka003.geometry} material={materials['Desk wood']} />
            <mesh castShadow receiveShadow geometry={nodes.Kostka003_1.geometry} material={materials['Frozen white metal']} />
          </group>
        </RigidBody>
        <group position={[18.319, 5, -31.616]}>
          <mesh castShadow receiveShadow geometry={nodes.Plane049.geometry} material={materials['Office Chair_Fabric']} />
          <mesh castShadow receiveShadow geometry={nodes.Plane049_1.geometry} material={materials.PaletteMaterial001} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials['Cabinet_Old White Metal']} position={[25.613, 5.358, -38.106]} scale={0.294} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder003.geometry} material={materials['Cabinet_Die-cast aluminum 2']} position={[25.613, 5.279, -37.812]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.908} />
        <mesh castShadow receiveShadow geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[25.613, 5.063, -38.108]} scale={0.908} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={materials.PaletteMaterial002} position={[25.613, 5.064, -38.086]} scale={0.908} />
        <group position={[22.086, 7.002, -38.368]} scale={1.684}>
          <mesh castShadow receiveShadow geometry={nodes.Cube028.geometry} material={materials.PaletteMaterial003} />
          <mesh castShadow receiveShadow geometry={nodes.Cube028_1.geometry} material={materials.FirstAidSticker} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.FirstAidSupply.geometry} material={materials.FirstAidSupply2} position={[22.134, 6.985, -38.31]} rotation={[Math.PI / 2, 0, 0]} scale={1.684} />
        <mesh castShadow receiveShadow geometry={nodes.FirstAidSupply016.geometry} material={materials.FirstAidSupply1} position={[22.076, 7.144, -38.309]} rotation={[Math.PI / 2, 0, 0]} scale={1.684} />
        <mesh castShadow receiveShadow geometry={nodes.FirstAidSupply026.geometry} material={materials.FirstAidSupply3} position={[21.971, 6.758, -38.298]} rotation={[0, -0.05, 0]} scale={1.684} />
        <group position={[20.429, 5.049, -34.352]} rotation={[Math.PI / 2, 0, 0]} scale={[1.171, 1.336, 1.336]}>
          <RigidBody colliders='cuboid' type='fixed'>
            <mesh castShadow receiveShadow geometry={nodes.Plane007.geometry} material={materials['4G Glass']} />
          </RigidBody>
          <mesh castShadow receiveShadow geometry={nodes.Plane007_1.geometry} material={materials.PaletteMaterial004} />
          <mesh castShadow receiveShadow geometry={nodes.Plane007_2.geometry} material={materials.PaletteMaterial005} />
          <mesh castShadow receiveShadow geometry={nodes.Plane007_3.geometry} material={materials['Marble Finish']} />
          <mesh castShadow receiveShadow geometry={nodes.Plane007_4.geometry} material={materials['Melamine Black']} />
        </group>
        <RigidBody colliders='cuboid' type='fixed'>
          <mesh castShadow receiveShadow geometry={nodes['File_Cabinets-Freepolyorg'].geometry} material={materials['01 - Default']} position={[25.073, 5, -38.043]} />
        </RigidBody>
        <RigidBody colliders='cuboid' type='dynamic' mass={2}>
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} position={[23.358, 6.898, -34.352]} rotation={[0, Math.PI / 4, 0]} scale={0.291} />
        </RigidBody>
        <instancedMesh args={[nodes['706336_w'].geometry, materials.FirstAidSupply3, 5]} castShadow receiveShadow instanceMatrix={nodes['706336_w'].instanceMatrix} />
        <instancedMesh args={[nodes['z0073-24-Unit-First-Aid-Kit-OSHA-Metal-Box014'].geometry, materials.FirstAidSupply2, 5]} castShadow receiveShadow instanceMatrix={nodes['z0073-24-Unit-First-Aid-Kit-OSHA-Metal-Box014'].instanceMatrix} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Asset_lab_industri-transformed.glb')
