/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/Asset_labkom_d.glb --transform --shadows --keepgroups 
Files: /home/TA/resource/Laboratory/Asset_labkom_d.glb [68.72MB] > Asset_labkom_d-transformed.glb [10.83MB] (84%)
*/

import { useState, useEffect } from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { RigidBody } from '@react-three/rapier'

export function LabkomD(props) {
  const { nodes, materials } = useGLTF('models/Asset_labkom_d-transformed.glb')

  const [idVideo, setIdVideo] = useState(1)

  const vidTexture = useVideoTexture(`/videos/video_${idVideo}.mp4`)

  useEffect(() => {
    console.log('rendered')
  }, [])

  const changeVideo = (event) => {
    if (idVideo === 4) {
      setIdVideo(1)
      return;
    }
    setIdVideo(idVideo + 1)
  }

  useFrame(() => {
    // 
  }, 15)
  return (
    <group {...props} dispose={null}>
      <group>
        {tablePosition.map((table, id) => (
          <RigidBody key={id} colliders='cuboid' type='fixed' position={[...table.position]} rotation={[0, Math.PI / 2, 0]}>
            <group>
              <mesh castShadow receiveShadow geometry={nodes.Kostka004.geometry} material={materials['Desk wood']} />
              <mesh castShadow receiveShadow geometry={nodes.Kostka004_1.geometry} material={materials['Frozen white metal']} />
            </group>
          </RigidBody>
        ))}
      </group>
    </group>
  )
}

useGLTF.preload('models/Asset_labkom_d-transformed.glb')


const tablePosition = [
  {
    position: [24.3923, 9.5, -37.634],
    rotation: [0, Math.PI / 2, 0]
  },
  {
    position: [25.5748, 9.5, -32.6885],
    rotation: [0, Math.PI / 2, 0]
  },

  {
    position: [22.5903, 9.5, -37.634],
    rotation: [0, Math.PI / 2, 0]
  },
  {
    position: [22.5903, 9.5, -32.6885],
    rotation: [0, Math.PI / 2, 0]
  },

  {
    position: [20.7883, 9.5, -37.634],
    rotation: [0, Math.PI / 2, 0]
  },
  {
    position: [20.7883, 9.5, -32.6885],
    rotation: [0, Math.PI / 2, 0]
  },
]