/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/BigLab.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/BigLab.glb [5.12MB] > BigLab-transformed.glb [1.33MB] (74%)
*/

import { useGLTF } from '@react-three/drei'
import { RigidBody } from "@react-three/rapier"
import { Plane } from "@react-three/drei"

export function BigLab(props) {
  const { nodes, materials } = useGLTF('models/BigLab-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Lab.geometry} material={materials['Plaster labs']} />
      <mesh castShadow receiveShadow geometry={nodes['Lab-top'].geometry} material={materials['Plaster labs top']} position={[-0.092, 4.15, 0]} />
      <RigidBody colliders='hull' type='fixed'>
        <Plane args={[20, 20, 20]} rotation-x={-Math.PI / 2} receiveShadow>
          <meshStandardMaterial color='whitesmoke' />
        </Plane>
      </RigidBody>
    </group>
  )
}

useGLTF.preload('models/BigLab-transformed.glb')
