/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../export/CabinetClose.glb --transform --shadows 
Files: ../export/CabinetClose.glb [4.64MB] > CabinetClose-transformed.glb [199.76KB] (96%)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function CloseCabinet(props) {
  const { nodes, materials } = useGLTF('models/CabinetClose-transformed.glb')
  useFrame(() => {
    // 
  }, 16)
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Body.geometry} material={materials.cabinet_body} rotation={[-Math.PI, 0, -Math.PI]} scale={0.843} />
      <mesh castShadow receiveShadow geometry={nodes.Body_L_hinge.geometry} material={materials.cabinet_handles} rotation={[-Math.PI, 0, -Math.PI]} scale={0.843} />
    </group>
  )
}

useGLTF.preload('models/CabinetClose-transformed.glb')
