/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../export/CabinetBook.glb --transform --shadows 
Files: ../export/CabinetBook.glb [3.16MB] > CabinetBook-transformed.glb [350.51KB] (89%)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function CabinetBook(props) {
  const { nodes, materials } = useGLTF('models/CabinetBook-transformed.glb')
  useFrame(() => {
    // 
  }, 12)
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['File_Cabinets-Freepolyorg'].geometry} material={materials['01 - Default']} />
    </group>
  )
}

useGLTF.preload('models/CabinetBook-transformed.glb')
