/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../export/CabinetBook.glb --transform --shadows 
Files: ../export/CabinetBook.glb [3.24MB] > CabinetBook-transformed.glb [313.03KB] (90%)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function CabinetBook(props) {
  const { nodes, materials } = useGLTF('models/CabinetBook-transformed.glb')
  useFrame(() => {
    // 
  }, 18)
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Drawer_Green.geometry} material={materials.Green_New} />
    </group>
  )
}

useGLTF.preload('models/CabinetBook-transformed.glb')
