/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/CupboardDark.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/CupboardDark.glb [2.77MB] > CupboardDark-transformed.glb [300.22KB] (89%)
*/

import { useGLTF } from '@react-three/drei'

export function Cupboard(props) {
  const { nodes, materials } = useGLTF('models/CupboardDark-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cupboard_900__450_1800_mm_Half_Glass_Door.geometry} material={materials.GWC_Cupboard_05} rotation={[Math.PI, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('models/CupboardDark-transformed.glb')
