/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../export/desk_lathe_animated.glb --transform --shadows 
Files: ../export/desk_lathe_animated.glb [20.59MB] > desk_lathe_animated-transformed.glb [1.22MB] (94%)
Author: kg007 (https://sketchfab.com/kg007)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desk-lathe-animated-5ba193e012a84dae822ff3c2ea7a7959
Title: Desk_lathe_Animated
*/

import { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function LatheMachine(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/desk_lathe_animated-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode" scale={1.396}>
          <group name="defaultMaterial001_4" position={[0.35, -0.188, 0.337]}>
            <mesh name="Object_9" castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials['02___Default']} />
          </group>
          <group name="defaultMaterial002_5" position={[0.405, 0.012, 0.368]}>
            <mesh name="Object_11" castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials['02___Default']} />
          </group>
          <group name="defaultMaterial003_6" position={[0.929, 0.172, -0.127]}>
            <mesh name="Object_13" castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials['02___Default']} />
          </group>
          <group name="defaultMaterial005_8">
            <group name="defaultMaterial004_7">
              <mesh name="Object_17" castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials['02___Default']} />
            </group>
            <mesh name="Object_15" castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials['02___Default']} />
          </group>
          <group name="defaultMaterial007_9" position={[0.21, 0, 0]}>
            <mesh name="Object_19" castShadow receiveShadow geometry={nodes.Object_19.geometry} material={materials['02___Default']} />
          </group>
          <group name="defaultMaterial008_11" position={[-0.266, 0.172, -0.127]}>
            <group name="Cylinder_10" position={[-0.073, 0, 0]} rotation={[0, 0, -Math.PI / 2]} scale={0.039}>
              <mesh name="Object_23" castShadow receiveShadow geometry={nodes.Object_23.geometry} material={materials['02___Default']} />
            </group>
            <mesh name="Object_21" castShadow receiveShadow geometry={nodes.Object_21.geometry} material={materials['02___Default']} />
          </group>
          <group name="defaultMaterial009_12" position={[-0.631, -0.02, 0.317]}>
            <mesh name="Object_25" castShadow receiveShadow geometry={nodes.Object_25.geometry} material={materials['02___Default']} />
          </group>
          <group name="defaultMaterial011_15" position={[0.21, 0, 0.003]}>
            <group name="defaultMaterial010_14">
              <group name="defaultMaterial006_13">
                <mesh name="Object_31" castShadow receiveShadow geometry={nodes.Object_31.geometry} material={materials['02___Default']} />
              </group>
              <mesh name="Object_29" castShadow receiveShadow geometry={nodes.Object_29.geometry} material={materials['02___Default']} />
            </group>
            <mesh name="Object_27" castShadow receiveShadow geometry={nodes.Object_27.geometry} material={materials['02___Default']} />
          </group>
          <group name="Bolt_16" position={[0.343, 0.172, -0.127]} rotation={[0, 0, -Math.PI / 2]} scale={0.017}>
            <mesh name="Object_33" castShadow receiveShadow geometry={nodes.Object_33.geometry} material={materials['02___Default']} />
          </group>
        </group>
        <mesh name="Object_7" castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials['02___Default']} scale={1.396} />
      </group>
    </group>
  )
}

useGLTF.preload('models/desk_lathe_animated-transformed.glb')
