/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../export/drill_press.glb --transform --shadows 
Files: ../export/drill_press.glb [2.91MB] > drill_press-transformed.glb [127.5KB] (96%)
Author: Scanamatics (https://sketchfab.com/jake.martinez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/drill-press-c89d0f20cb9e421c94606540df665d82
Title: Drill Press
*/

import { useGLTF } from '@react-three/drei'

export function DrillPress(props) {
  const { nodes, materials } = useGLTF('models/drill_press-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.model_Material_u1_v1} position={[27.195, 0, -12.806]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('models/drill_press-transformed.glb')
