/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/GlassTable.glb --shadows 
Author: NoobiePie (https://sketchfab.com/NoobiePie)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-glass-table-6acac6d9201e448b92dff859b6f63aad
Title: Low-Poly Glass Table
*/

import { useGLTF } from '@react-three/drei'

export function GlassTable(props) {
  const { nodes, materials } = useGLTF('models/GlassTable-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 123.7, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={90}>
          <mesh castShadow receiveShadow geometry={nodes.Glass_Glass_0.geometry} material={materials.Glass} />
          <mesh castShadow receiveShadow geometry={nodes.Pillars_Pillars_0.geometry} material={materials.Pillars} position={[0, 0, -0.13]} scale={1.111} />
          <mesh castShadow receiveShadow geometry={nodes.SecondGlass_Glass_0.geometry} material={materials.Glass} position={[0, 0, -0.811]} scale={[0.889, 0.889, 1.111]} />
          <mesh castShadow receiveShadow geometry={nodes.Leg_2_Legs_0.geometry} material={materials.Legs} position={[0, -1.556, -0.408]} scale={1.111} />
          <mesh castShadow receiveShadow geometry={nodes.Leg_1_Legs_0.geometry} material={materials.Legs} position={[0, 1.556, -0.408]} scale={1.111} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/GlassTable-transformed.glb')
