/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/GreyCabinet.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/GreyCabinet.glb [4.24MB] > GreyCabinet-transformed.glb [701.89KB] (83%)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { RigidBody } from "@react-three/rapier"

export function GreyCabinet(props) {
  const { nodes, materials } = useGLTF('models/GreyCabinet-transformed.glb')
  useFrame(() => {
    // 
  }, 10)
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]}>
        <RigidBody colliders='cuboid' type='fixed'>
          <mesh castShadow receiveShadow geometry={nodes.Cube026.geometry} material={materials['Persian walnut PBR texture seamless.003']} />
        </RigidBody>
        <mesh castShadow receiveShadow geometry={nodes.Cube026_1.geometry} material={materials['metal.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube026_2.geometry} material={materials['white paint.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube026_3.geometry} material={materials['black plastic.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube026_4.geometry} material={materials['Persian walnut PBR texture seamless.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube026_5.geometry} material={materials['Basic glass']} />
      </group>
    </group>
  )
}

useGLTF.preload('models/GreyCabinet-transformed.glb')
