/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/helmet.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/helmet.glb [21.05MB] > helmet-transformed.glb [458.6KB] (98%)
Author: SuperMopsek (https://sketchfab.com/pajamakeke)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/construction-helmet-orange-2f9546f0aa9e4dbdade316e1b9d59f04
Title: Construction Helmet (Orange)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Helmet(props) {
  const { nodes, materials } = useGLTF('models/helmet-transformed.glb')
  useFrame(() => {
    // 
  }, 12)
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.tz012_Helmet_0.geometry} material={materials.Helmet} rotation={[-Math.PI / 2, 0, 0]} scale={1.452} />
    </group>
  )
}

useGLTF.preload('models/helmet-transformed.glb')
