/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/LongSofa.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/LongSofa.glb [5.5MB] > LongSofa-transformed.glb [1.81MB] (67%)
*/

import { useGLTF } from '@react-three/drei'

export function LongSofa(props) {
  const { nodes, materials } = useGLTF('models/LongSofa-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Leg_part.geometry} material={materials['Black Painted Wood']} />
      <mesh castShadow receiveShadow geometry={nodes.Levellers.geometry} material={materials.Button} />
      <mesh castShadow receiveShadow geometry={nodes.Seat_part.geometry} material={materials.Fabric} />
    </group>
  )
}

useGLTF.preload('models/LongSofa-transformed.glb')
