/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/MiniApartement.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/MiniApartement.glb [2.35MB] > MiniApartement-transformed.glb [228.9KB] (90%)
*/

import { useGLTF } from '@react-three/drei'

export function MiniApartement(props) {
  const { nodes, materials } = useGLTF('models/MiniApartement-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.OfficeBuilding2001.geometry} material={materials._White} scale={0.015} />
      <mesh castShadow receiveShadow geometry={nodes.OfficeBuilding2002.geometry} material={materials._Black} scale={0.015} />
      <mesh castShadow receiveShadow geometry={nodes.OfficeBuilding2003.geometry} material={nodes.OfficeBuilding2003.material} scale={0.015} />
      <mesh castShadow receiveShadow geometry={nodes.OfficeBuilding2009.geometry} material={materials.aluminum2} scale={0.015} />
      <mesh castShadow receiveShadow geometry={nodes.OfficeBuilding2012.geometry} material={materials['StoneTile.001']} scale={0.015} />
    </group>
  )
}

useGLTF.preload('models/MiniApartement-transformed.glb')
