/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/MiniHouse.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/MiniHouse.glb [8.87MB] > MiniHouse-transformed.glb [1.41MB] (84%)
*/

import { useGLTF } from '@react-three/drei'

export function MiniHouse(props) {
  const { nodes, materials } = useGLTF('models/MiniHouse-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Circle.geometry} material={materials.PaletteMaterial001} position={[-0.204, 0, -0.232]} scale={0.02} />
      <group position={[0.049, 0.003, 0.266]} scale={0.02}>
        <mesh castShadow receiveShadow geometry={nodes.DoorFrane001.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.DoorFrane001_1.geometry} material={materials.PaletteMaterial003} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.doors_int.geometry} material={materials['wood dark']} position={[0.065, 0.003, -0.204]} scale={0.02} />
      <mesh castShadow receiveShadow geometry={nodes.kam_obklad.geometry} material={materials.Omitka} position={[0.174, 0.03, -0.213]} scale={0.02} />
      <mesh castShadow receiveShadow geometry={nodes.kolejnice.geometry} material={materials['AluminumBrushed kolejnice']} position={[-0.177, 0.054, -0.254]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.001, 0.001, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.okenice.geometry} material={materials.wood} position={[0.177, 0.023, -0.226]} rotation={[0, -Math.PI / 2, 0]} scale={0.02} />
      <instancedMesh args={[nodes.invalid017.geometry, materials.PaletteMaterial001, 6]} castShadow receiveShadow instanceMatrix={nodes.invalid017.instanceMatrix} />
      <instancedMesh args={[nodes.invalid017_1.geometry, materials.PaletteMaterial002, 6]} castShadow receiveShadow instanceMatrix={nodes.invalid017_1.instanceMatrix} />
      <instancedMesh args={[nodes.invalid021.geometry, materials.PaletteMaterial001, 6]} castShadow receiveShadow instanceMatrix={nodes.invalid021.instanceMatrix} />
      <instancedMesh args={[nodes.invalid021_1.geometry, materials.PaletteMaterial002, 6]} castShadow receiveShadow instanceMatrix={nodes.invalid021_1.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('models/MiniHouse-transformed.glb')
