/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/OfficeChair.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/OfficeChair.glb [3.67MB] > OfficeChair-transformed.glb [779.21KB] (79%)
*/

import { useGLTF } from '@react-three/drei'

export function OfficeChair(props) {
  const { nodes, materials } = useGLTF('models/OfficeChair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane047.geometry} material={materials['Office Chair_Fabric']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane047_1.geometry} material={materials['Office Chair_Metal']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane047_2.geometry} material={materials['Office Chair_Painted Metal']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane047_3.geometry} material={materials['Office Chair_Plastic']} />
    </group>
  )
}

useGLTF.preload('models/OfficeChair-transformed.glb')
