/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/Plotter.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/Plotter.glb [12.88MB] > Plotter-transformed.glb [502.09KB] (96%)
Author: ARComputerFundamentals (https://sketchfab.com/adilaijaz10)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plotter-d5c61642d4684a81a1cdf3eb2fddb9dd
Title: plotter
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Plotter(props) {
  const { nodes, materials } = useGLTF('models/Plotter-transformed.glb')
  useFrame(() => {
    // 
  }, 20)
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['3D_PLOTTER_SCOCCA_PLASTICA_OPACA_BIANCA_0'].geometry} material={materials.PLASTICA_OPACA_BIANCA} position={[-0.662, 0.903, -0.225]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes['3D_PLOTTER_GAMBE_FERRO_by_BRAVEFART_0'].geometry} material={materials.FERRO_by_BRAVEFART} position={[-0.661, 0.495, -0.194]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes['3D_PLOTTER_SCHERMO_SCREEN_0'].geometry} material={materials.SCREEN} position={[0.048, 0.988, -0.064]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes['3D_PLOTTER_TASTI_GOMMA_GOMMA_BIANCA_0'].geometry} material={materials.GOMMA_BIANCA} position={[-0.003, 0.979, -0.051]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('models/Plotter-transformed.glb')
