/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../export/3d_printer.glb --transform --shadows --output PrinterThree.jsx 
Files: ../export/3d_printer.glb [2.26MB] > 3d_printer-transformed.glb [370.55KB] (84%)
Author: Gregsterius (https://sketchfab.com/Gregsterius)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-printer-0e825a8d48b14bee883a131fe029d4fc
Title: 3D Printer
*/

import { useGLTF } from '@react-three/drei'

export function PrinterThree(props) {
  const { nodes, materials } = useGLTF('models/3d_printer-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube_Black_base_0.geometry} material={materials.PaletteMaterial001} position={[0, 394.078, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh castShadow receiveShadow geometry={nodes.Cube008_Display_0.geometry} material={materials.PaletteMaterial002} position={[0, 311.132, 1222.317]} rotation={[-2.006, 0, Math.PI]} scale={[-220.507, 10.584, 139.837]} />
      <instancedMesh args={[nodes.Cylinder004_Shiny_metal_0.geometry, materials.PaletteMaterial001, 5]} castShadow receiveShadow instanceMatrix={nodes.Cylinder004_Shiny_metal_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('models/3d_printer-transformed.glb')
