/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/SingleDoor.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/SingleDoor.glb [4.96MB] > SingleDoor-transformed.glb [577.4KB] (88%)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function SingleDoor(props) {
  const { nodes, materials } = useGLTF('models/SingleDoor-transformed.glb')
  useFrame(() => {
    // 
  }, 3)
  return ( 
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Door_double002.geometry} material={materials['Afromosia Fine Wood']} />
      <mesh castShadow receiveShadow geometry={nodes.Handle002.geometry} material={materials.Handle_Metal} position={[0.022, 1.257, 0.065]} scale={1.962} />
      <mesh castShadow receiveShadow geometry={nodes.Plane001.geometry} material={materials['Glass Door']} position={[0.02, 1.292, 0.222]} rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('models/SingleDoor-transformed.glb')
