/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/SingleSofa.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/SingleSofa.glb [43.45MB] > SingleSofa-transformed.glb [8.84MB] (80%)
*/

import { useGLTF } from '@react-three/drei'

export function SingleSofa(props) {
  const { nodes, materials } = useGLTF('models/SingleSofa-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube056.geometry} material={materials['Fabric.001']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube056_1.geometry} material={materials.Wood} />
    </group>
  )
}

useGLTF.preload('models/SingleSofa-transformed.glb')
