/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/SmallLab.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/SmallLab.glb [5.13MB] > SmallLab-transformed.glb [1.33MB] (74%)
*/

import { useGLTF } from '@react-three/drei'
import { CuboidCollider, RigidBody } from '@react-three/rapier'

export function SmallLab(props) {
  const { nodes, materials } = useGLTF('models/SmallLab-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody colliders={false} type="fixed">
        <mesh castShadow receiveShadow geometry={nodes.Lab_small.geometry} material={materials['Plaster lab small']} position={[0, 0, 0.003]} />
        <CuboidCollider args={[0.6, 2, 5.8]} position={[4.2, 2, 0]} />
        <CuboidCollider args={[0.2, 2, 8]} position={[-4.6, 2, 0]} />
        <CuboidCollider args={[5, 2, 0.2]} position={[0, 2, 8]} />
        <CuboidCollider args={[5, 2, 0.2]} position={[0, 2, -8]} />
        <CuboidCollider args={[5, 2, 0.2]} position={[0, 2, 0]} />
      </RigidBody>
      <mesh castShadow receiveShadow geometry={nodes['Lab-top_small'].geometry} material={materials['Plaster lab small top']} position={[-0.092, 4.15, 0]} />
    </group>
  )
}

useGLTF.preload('models/SmallLab-transformed.glb')
