/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/SmallLab.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/SmallLab.glb [5.13MB] > SmallLab-transformed.glb [1.33MB] (74%)
*/

import { useGLTF } from '@react-three/drei'

export function SmallLab(props) {
  const { nodes, materials } = useGLTF('models/SmallLab-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Lab_small.geometry} material={materials['Plaster lab small']} position={[0, 0, 0.003]} />
      <mesh castShadow receiveShadow geometry={nodes['Lab-top_small'].geometry} material={materials['Plaster lab small top']} position={[-0.092, 4.15, 0]} />
    </group>
  )
}

useGLTF.preload('models/SmallLab-transformed.glb')
