/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/StudentChair.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/StudentChair.glb [176.99KB] > StudentChair-transformed.glb [36.47KB] (79%)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function ClassChair(props) {
  const { nodes, materials } = useGLTF('models/StudentChair-transformed.glb')
  useFrame(() => {
    // 
  }, 12)
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.597, -0.5]} scale={0.7}>
        <mesh castShadow receiveShadow geometry={nodes.Plane110_Plane096.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Plane110_Plane096_1.geometry} material={materials.PaletteMaterial001} />
      </group>
    </group>
  )
}

useGLTF.preload('models/StudentChair-transformed.glb')
