/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../export/TableShelf.glb --transform --shadows 
Files: ../export/TableShelf.glb [8.68MB] > TableShelf-transformed.glb [1.39MB] (84%)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { RigidBody } from '@react-three/rapier'

export function TableShelf(props) {
  const { nodes, materials } = useGLTF('models/TableShelf-transformed.glb')
  useFrame(() => {
    // 
  }, 22)
  return (
    <group {...props} dispose={null}>
      <RigidBody colliders='cuboid' type='fixed'>
        <mesh castShadow receiveShadow geometry={nodes.connect.geometry} material={materials.Black_Paint} rotation={[-Math.PI, 0, -Math.PI]} />
      </RigidBody>
      <group position={[-0.605, 0.777, -0.177]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh012.geometry} material={materials.Handle_mat} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh012_1.geometry} material={materials.Paint_edge_mat} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh012_2.geometry} material={materials.Paint_mat} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh012_3.geometry} material={materials.Key_metal} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.table.geometry} material={materials.Main_table} rotation={[-Math.PI, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('models/TableShelf-transformed.glb')
