/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/TableDesk.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/TableDesk.glb [5.16MB] > TableDesk-transformed.glb [477.03KB] (91%)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { RigidBody } from '@react-three/rapier'

export function TableDesk(props) {
  const { nodes, materials } = useGLTF('models/TableDesk-transformed.glb')
  useFrame(() => {
    // 
  }, 20)
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, Math.PI / 2, 0]}>
        <RigidBody colliders='cuboid' type='fixed'>
          <mesh castShadow receiveShadow geometry={nodes.Kostka004.geometry} material={materials['Desk wood']} />
        </RigidBody>
        <mesh castShadow receiveShadow geometry={nodes.Kostka004_1.geometry} material={materials['Frozen white metal']} />
      </group>
    </group>
  )
}

useGLTF.preload('models/TableDesk-transformed.glb')
