/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/TableReading.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/TableReading.glb [1.39MB] > TableReading-transformed.glb [136.6KB] (90%)
*/

import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function TableReading(props) {
  const { nodes, materials } = useGLTF('models/TableReading-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody colliders='cuboid' type='fixed'>
        <mesh castShadow receiveShadow geometry={nodes.Cube029.geometry} material={materials['Grainy Wood']} />
      </RigidBody>
      <mesh castShadow receiveShadow geometry={nodes.Cube029_1.geometry} material={materials['Grainy PVC']} />
    </group>
  )
}

useGLTF.preload('models/TableReading-transformed.glb')
