/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/sketchfab/whiteboard.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/sketchfab/whiteboard.glb [162.55KB] > whiteboard-transformed.glb [17.6KB] (89%)
Author: tankop1 (https://sketchfab.com/tankop1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-whiteboard-1cbf089ec4b741ad9d092d15db6d55ba
Title: Low Poly Whiteboard
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Whiteboard(props) {
  const { nodes, materials } = useGLTF('models/whiteboard-transformed.glb')
  useFrame(() => {
    // 
  }, 16)
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Corner_Horizontal_Material_0.geometry} material={materials.PaletteMaterial001} position={[-0.001, 1.58, 1.372]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.054, 0.05, 0.041]} />
    </group>
  )
}

useGLTF.preload('models/whiteboard-transformed.glb')
