/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/assets/WoodShelf.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/assets/WoodShelf.glb [39.04KB] > WoodShelf-transformed.glb [2.48KB] (94%)
*/

import { useGLTF } from '@react-three/drei'

export function WoodShelf(props) {
  const { nodes, materials } = useGLTF('models/WoodShelf-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Wooden_Shelf.geometry} material={materials['Procedural Wood']} rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('models/WoodShelf-transformed.glb')
