/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../../asset/Adam.glb --transform --shadows 
Files: ../../asset/Adam.glb [36.21MB] > Adam-transformed.glb [2.33MB] (94%)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations, useKeyboardControls } from '@react-three/drei'
import { CapsuleCollider, RigidBody, vec3, quat } from '@react-three/rapier'
import { useFrame } from '@react-three/fiber'
import { Vector3 } from "three"

const charRotate = quat()
const vectorMovement = new Vector3()

export function Adam(props) {
  // Refs
  const group = useRef()
  const adam = useRef()
  const colliderRef = useRef()

  // useGLTF
  const { nodes, materials, animations } = useGLTF('models/Adam-transformed.glb')
  const { actions } = useAnimations(animations, group)

  // Keyboard controls
  const [, getKey] = useKeyboardControls()

  // Loop frame
  useFrame((state, delta) => {
    const { forward, backward, left, right, jump, run } = getKey()
    const offsetCam = new Vector3(0, 0.3, -0.1)
    const currentPos = vec3(adam.current.translation())
    const currentRotate = quat(adam.current.rotation())
    const currentVeloc = vec3(adam.current.linvel())

    offsetCam.applyQuaternion(currentRotate)
    offsetCam.add(currentPos)
    state.camera.position.copy(offsetCam)

    vectorMovement.set(right - left, 0, backward - forward).multiplyScalar((run ? 50 : 20) * delta)
    vectorMovement.applyQuaternion(currentRotate)
    adam.current.setLinvel({ ...vectorMovement, y: currentVeloc.y }, true)

    charRotate.setFromEuler(state.camera.rotation)
    adam.current.setRotation(quat({ ...currentRotate, y: charRotate.y, w: charRotate.w }), true)
  }, 2)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <RigidBody ref={adam} colliders={false} type='dynamic' position-y={1} enabledRotations={[false, false, false]} friction={0} name='Adam'>
          <CapsuleCollider ref={colliderRef} args={[0.1, 0.08]} />
          <group name="Armature" rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.003} position-y={-0.18}>
            <primitive object={nodes.mixamorigHips} />
          </group>
          <skinnedMesh name="Ch23_Belt" geometry={nodes.Ch23_Belt.geometry} material={materials.Ch23_body} skeleton={nodes.Ch23_Belt.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
          <skinnedMesh name="Ch23_Body" geometry={nodes.Ch23_Body.geometry} material={materials.Ch23_body} skeleton={nodes.Ch23_Body.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
          <skinnedMesh name="Ch23_Eyelashes" geometry={nodes.Ch23_Eyelashes.geometry} material={materials.Ch23_hair} skeleton={nodes.Ch23_Eyelashes.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
          <skinnedMesh name="Ch23_Hair" geometry={nodes.Ch23_Hair.geometry} material={materials.Ch23_hair} skeleton={nodes.Ch23_Hair.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
          <skinnedMesh name="Ch23_Pants" geometry={nodes.Ch23_Pants.geometry} material={materials.Ch23_body} skeleton={nodes.Ch23_Pants.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
          <skinnedMesh name="Ch23_Shirt" geometry={nodes.Ch23_Shirt.geometry} material={materials.Ch23_body} skeleton={nodes.Ch23_Shirt.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
          <skinnedMesh name="Ch23_Shoes" geometry={nodes.Ch23_Shoes.geometry} material={materials.Ch23_body} skeleton={nodes.Ch23_Shoes.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
          <skinnedMesh name="Ch23_Suit" geometry={nodes.Ch23_Suit.geometry} material={materials.Ch23_body} skeleton={nodes.Ch23_Suit.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        </RigidBody>
      </group>
    </group>
  )
}

useGLTF.preload('models/Adam-transformed.glb')
