/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../../asset/assets/Ball.glb --transform --shadows 
Files: ../../asset/assets/Ball.glb [9.04MB] > Ball-transformed.glb [1.19MB] (87%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Ball(props) {
  const { nodes, materials } = useGLTF('models/Ball-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody colliders='ball' type={props.dynamic? 'dynamic':'kinematicPosition'} userData={{type: 'rigid_parent'}}>
        <group position={[-1.244, 0.499, -1.518]} scale={0.7} onClick={(event) => props.getEvent(event.eventObject)}>
          <mesh castShadow receiveShadow geometry={nodes.Mesh.geometry} material={materials.blanco} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh_1.geometry} material={materials.tango} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh_2.geometry} material={materials.adidas} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh_3.geometry} material={materials.official} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh_4.geometry} material={materials.fifa} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh_5.geometry} material={materials.motivo} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh_6.geometry} material={materials.costura} />
        </group>
      </RigidBody>
    </group>
  )
}

useGLTF.preload('models/Ball-transformed.glb')
