/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/Ball.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/Ball.glb [1.79MB] > Ball-transformed.glb [539.61KB] (70%)
*/

import { useGLTF } from '@react-three/drei'
import { BallCollider, RigidBody } from '@react-three/rapier'

export function Ball(props) {
  const { nodes, materials } = useGLTF('models/Ball-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody colliders={false} type={props.dynamic ? "dynamic" : "kinematicPosition"} position={[0, 0.5, -1]} userData={{ type: 'rigid_parent' }}>
        <BallCollider args={[0.06]} />
        <mesh castShadow receiveShadow geometry={nodes.Football001.geometry} material={materials['3DModel_LowPoly']} rotation={[-Math.PI, 0, 0]} position-y={-0.05} scale={0.08} onClick={event => {
          props.getObject(event.eventObject.parent)
        }} />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('models/Ball-transformed.glb')
