/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/Book.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/Book.glb [7.69MB] > Book-transformed.glb [137.68KB] (98%)
*/

import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { Interactive } from '@react-three/xr'
import { toast } from 'react-toastify'

export function Book(props) {
  const { nodes, materials } = useGLTF('models/Book-transformed.glb')
  return (
    <Interactive
      onSelect={xrEvent => {
        if (xrEvent.intersection?.distance >= 0.18) {
          return;
        }
        const obj = xrEvent.intersection?.object.parent
        const index = xrEvent.target.index
        props.getObject(obj, index)
      }}
      onHover={(xrEvent) => {
        if ((xrEvent.intersection?.distance <= 0.18) && props.objectId === '') {
          toast.info('Klik trigger untuk ambil benda', { autoClose: 1000 })
        }
      }}
    >
      <RigidBody {...props} colliders='cuboid' type={props.dynamic ? "dynamic" : "kinematicPosition"} userData={{ type: 'rigid_parent' }}>
        <mesh castShadow receiveShadow geometry={nodes.Old_Book_ST_Ives.geometry} material={materials['Old Book: St. Ives']} scale={0.6}
          onClick={event => {
            if (event.distance <= 0.7) props.getObject(event.eventObject.parent)
          }}
          onPointerEnter={event => {
            if (props.objectId === '' && (event.distance <= 0.7)) toast.info('Klik kiri untuk ambil benda', { autoClose: 1000 })
          }} />
      </RigidBody>
    </Interactive>
  )
}

useGLTF.preload('models/Book-transformed.glb')
