/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/Book.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/Book.glb [1.52MB] > Book-transformed.glb [164.02KB] (89%)
*/

import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Book(props) {
  const { nodes, materials } = useGLTF('models/Book-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody colliders='cuboid' type={props.dynamic? 'dynamic':'kinematicPosition'} userData={{type: 'rigid_parent'}}>
        <mesh castShadow receiveShadow geometry={nodes['Book_-_Encyclopedia'].geometry} material={materials.DefaultMaterial} position={[-1.242, 0.434, 0.624]} rotation={[0, 1.571, 0]} scale={0.08} onClick={(event) => props.getEvent(event.eventObject)} />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('models/Book-transformed.glb')
