/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/Cover.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/Cover.glb [20.64MB] > Cover-transformed.glb [2.88MB] (86%)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Cover(props) {
  const { nodes, materials } = useGLTF('models/Cover-transformed.glb')
  useFrame(() => {
    // 
  }, 3)
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['cover-front'].geometry} material={materials.Material} position={[-4.262, 1.77, -7.16]} scale={0.3} />
      <group position={[-8.142, 2.88, 6.44]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube012.geometry} material={materials['Glass dark']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube012_1.geometry} material={materials.Plastic} />
      </group>
      <group position={[-18.416, 7.64, -3.882]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube024.geometry} material={materials.painted_metal_shutter} />
        <mesh castShadow receiveShadow geometry={nodes.Cube024_1.geometry} material={materials['Black Nickel']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes['cover-audit'].geometry} material={materials['Orange grain plastic']} position={[-12.155, 3.18, -3.882]} />
    </group>
  )
}

useGLTF.preload('models/Cover-transformed.glb')
