/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Door.glb --transform --shadows --keepgroups 
Files: /home/TA/resource/Door.glb [18.3MB] > Door-transformed.glb [1.15MB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Doors(props) {
  const { nodes, materials } = useGLTF('models/Door-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody colliders='trimesh' type='kinematicPosition' position={[-2.10128, 0.315001, -5.18722]}>
        <group name='Door'>
          <mesh castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={materials.Handle_Metal} position={[-0.015, 0.381, -0.003]} rotation={[Math.PI / 2, 0, 0]} scale={0.293} />
          <mesh castShadow receiveShadow geometry={nodes['Door-light'].geometry} material={materials['Afromosia Fine Wood']} />
          <mesh castShadow receiveShadow geometry={nodes['Glass-door-light'].geometry} material={materials.Glass} position={[-0.078, 0.486, 0]} />
        </group>
      </RigidBody>
    </group>
  )
}

useGLTF.preload('models/Door-transformed.glb')
