/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/Flower.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/Flower.glb [12.25MB] > Flower-transformed.glb [2.93MB] (76%)
*/

import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { toast } from 'react-toastify'

export function Flower(props) {
  const { nodes, materials } = useGLTF('models/Flower-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody colliders='cuboid' type={props.dynamic? 'dynamic':'kinematicPosition'}>
        <mesh castShadow receiveShadow geometry={nodes.Circle001.geometry} material={materials['Flower Vase_Vase']} position={[-1.244, 0.282, -1.518]}
          onClick={event => {
            if (event.distance <= 0.7) props.getObject(event.eventObject.parent)
          }}
          onPointerEnter={event => {
            if (props.objectId === '' && (event.distance <= 0.7)) toast.info('Klik kiri untuk ambil benda', {autoClose: 1000})
          }}
        />
        <mesh castShadow receiveShadow geometry={nodes.Cube005.geometry} material={materials.PaletteMaterial002} position={[-1.235, 0.404, -1.511]} rotation={[0.093, -0.213, -0.161]} scale={0.09} />
        <group position={[-1.211, 0.477, -1.501]} rotation={[-2.641, -0.405, 0.302]} scale={0.021}>
          <mesh castShadow receiveShadow geometry={nodes.Plane008.geometry} material={materials['Flower Vase_Assorted Color']} />
          <mesh castShadow receiveShadow geometry={nodes.Plane008_1.geometry} material={materials.PaletteMaterial001} />
        </group>
      </RigidBody>
    </group>
  )
}

useGLTF.preload('models/Flower-transformed.glb')
