/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Lab.glb --transform --shadows 
Files: /home/TA/resource/Lab.glb [7.33MB] > Lab-transformed.glb [425.16KB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { RigidBody } from '@react-three/rapier'

export function Labs(props) {
  const { nodes, materials } = useGLTF('models/Lab-transformed.glb')
  useFrame(() => {
    // 
  }, 2)
  return (
    <group {...props} dispose={null}>
      <RigidBody colliders='trimesh' type='fixed'>
        <group position={[10.904, 0.3, -3.486]}>
          <mesh castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Cube013_1.geometry} material={materials['ceramic room']} />
        </group>
      </RigidBody>
    </group>
  )
}

useGLTF.preload('models/Lab-transformed.glb')
