/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Lab.glb --transform --shadows 
Files: /home/TA/resource/Lab.glb [4.53MB] > Lab-transformed.glb [335.65KB] (93%)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Labs(props) {
  const { nodes, materials } = useGLTF('models/Lab-transformed.glb')
  useFrame(() => {
    // 
  }, 2)
  return (
    <group {...props} dispose={null}>
      <group position={[10.904, 0.3, -3.486]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials['Default white wall']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube013_1.geometry} material={materials['ceramic room']} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Lab-transformed.glb')
