/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/Labter.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/Labter.glb [11.84MB] > Labter-transformed.glb [2.41MB] (80%)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Labter(props) {
  const { nodes, materials } = useGLTF('models/Labter-transformed.glb')
  useFrame(() => {
    // 
  }, 1)
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.5, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane005.geometry} material={materials.Plaster} />
        <mesh castShadow receiveShadow geometry={nodes.Plane005_1.geometry} material={materials['ceramic floor 1']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane005_2.geometry} material={materials['Plaster wall floor 1']} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Labter-transformed.glb')
