/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/Labter.glb --shadows 
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { RigidBody } from '@react-three/rapier'

export function Labter(props) {
  const { nodes, materials } = useGLTF('models/Labter-transformed.glb')
  useFrame(() => {
    // 
  }, 1)
  return (
    <group {...props} dispose={null}>
      <RigidBody colliders='trimesh' type='fixed'>
        <group position={[0, 0.5, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.Plane005.geometry} material={materials['ceramic floor 1']} />
          <mesh castShadow receiveShadow geometry={nodes.Plane005_1.geometry} material={materials.Plaster} />
          <mesh castShadow receiveShadow geometry={nodes.Plane005_2.geometry} material={materials['Plaster wall floor 1']} />
        </group>
        <group position={[0, 5, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.Plane011.geometry} material={materials['ceramic floor 1']} />
          <mesh castShadow receiveShadow geometry={nodes.Plane011_1.geometry} material={materials['Plaster wall floor 1']} />
        </group>
        <group position={[0, 9.5, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.Plane012.geometry} material={materials['ceramic floor 1']} />
          <mesh castShadow receiveShadow geometry={nodes.Plane012_1.geometry} material={materials['Plaster wall floor 1']} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Floor_4.geometry} material={materials['Plaster wall floor 1']} position={[0, 14, 0]} />
        <group position={[-0.424, 7, 31.274]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh castShadow receiveShadow geometry={nodes.Cube004.geometry} material={materials['Plaster lppm']} />
          <mesh castShadow receiveShadow geometry={nodes.Cube004_1.geometry} material={materials['Black glass']} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Auditorium.geometry} material={materials['Plaster audit']} position={[-0.905, 9.5, 29.715]} />
        <mesh castShadow receiveShadow geometry={nodes.Kalterisasi.geometry} material={materials['Plaster labs']} position={[-0.399, 2.5, 34.133]} />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('models/Labter-transformed.glb')
