/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/Rooftop.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/Rooftop.glb [36.78MB] > Rooftop-transformed.glb [6MB] (84%)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Rooftop(props) {
  const { nodes, materials } = useGLTF('models/Rooftop-transformed.glb')
  useFrame(() => {
    // 
  }, 4)
  return (
    <group {...props} dispose={null}>
      <group position={[16.006, 4.425, -3.938]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials['Home Siding metal']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube002_1.geometry} material={materials['Black Nickel']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes['roof-top-tralis'].geometry} material={materials['Metal Frame']} position={[-4.837, 5.929, 1.543]} />
      <mesh castShadow receiveShadow geometry={nodes['roof-top'].geometry} material={materials['Plastic Blue']} position={[2.441, 6.017, 1.543]} />
    </group>
  )
}

useGLTF.preload('models/Rooftop-transformed.glb')
