/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../../asset/room.glb --transform --shadows 
Files: ../../asset/room.glb [13.17MB] > room-transformed.glb [496.76KB] (96%)
Author: jimbogies (https://sketchfab.com/jimbogies)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sitting-room-with-baked-textures-61fdbbef86b9496d80644492a84c916f
Title: Sitting Room with Baked Textures
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Room(props) {
  const { nodes, materials } = useGLTF('models/room-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody colliders='trimesh' type='fixed' friction={0}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={0.5} />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('models/room-transformed.glb')
