/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/Stair.glb --shadows 
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { RigidBody } from '@react-three/rapier'

export function Stair(props) {
  const { nodes, materials } = useGLTF('models/Stair-transformed.glb')
  useFrame(() => {
    // 
  }, 4)
  return (
    <group {...props} dispose={null}>
      <RigidBody colliders='trimesh' type='fixed'>
        <group position={[...props.pos]} rotation={[...props.rot]}>
          <mesh castShadow receiveShadow geometry={nodes.Cube011.geometry} material={materials['Marble Tiles Hungarian']} />
          <mesh castShadow receiveShadow geometry={nodes.Cube011_1.geometry} material={materials['Plaster stair']} />
        </group>
      </RigidBody>
    </group>
  )
}

useGLTF.preload('models/Stair-transformed.glb')
