/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/Table.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/Table.glb [42.44MB] > Table-transformed.glb [4.58MB] (89%)
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Tables(props) {
  const { nodes, materials } = useGLTF('models/Table-transformed.glb')
  useFrame(() => {
    // 
  }, 7)
  return (
    <group {...props} dispose={null}>
      <group position={[11.654, 3.555, 6.001]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane018.geometry} material={materials['Material.006']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane018_1.geometry} material={materials['Material.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane018_2.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Table-transformed.glb')
