/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/TV.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/TV.glb [2.3MB] > TV-transformed.glb [388.34KB] (83%)
*/

import { useGLTF } from '@react-three/drei'

export function TV(props) {
  const { nodes, materials } = useGLTF('models/TV-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.277, 0.166, 2.296]} rotation={[-Math.PI / 2, 0, -1.325]} scale={0.7}>
        <mesh castShadow receiveShadow geometry={nodes.book_cover005_1.geometry} material={materials['book_cover.005']} />
        <mesh castShadow receiveShadow geometry={nodes.book_cover005_2.geometry} material={materials.book_paper} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.book_cover006.geometry} material={materials['book_cover.006']} position={[0.277, 0.183, 2.296]} rotation={[-Math.PI / 2, 0, -1.458]} scale={0.7} />
      <mesh castShadow receiveShadow geometry={nodes.book_cover007.geometry} material={materials['book_cover.007']} position={[-0.681, 0.263, 2.309]} rotation={[-Math.PI / 2, 0, -0.615]} scale={0.7} />
      <mesh castShadow receiveShadow geometry={nodes.Cabinet_cover.geometry} material={materials['wood (Oak Matt Antracite Gray)']} position={[-0.214, 0.061, 2.32]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.7} />
      <mesh castShadow receiveShadow geometry={nodes.Cabinet1.geometry} material={materials.ceramic} position={[0.416, 0.068, 2.449]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.7} />
      <group position={[-0.214, 0.542, 2.333]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.7}>
        <mesh castShadow receiveShadow geometry={nodes.TV_1.geometry} material={materials['Screen (tv)']} />
        <mesh castShadow receiveShadow geometry={nodes.TV_2.geometry} material={materials.frame} />
      </group>
    </group>
  )
}

useGLTF.preload('models/TV-transformed.glb')
