/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/TV.glb --transform --shadows --keepgroups 
Files: /home/TA/resource/Laboratory/TV.glb [5.88MB] > TV-transformed.glb [680.42KB] (88%)
*/

import { useGLTF } from '@react-three/drei'

export function SmartTV(props) {
  const { nodes, materials } = useGLTF('models/TV-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.drawer.geometry} material={materials['CC0Textures/Wood029/2K-JPG']} position={[-0.21, 0.01, -2.1]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.391, 0.396, 0.396]} />
      <mesh castShadow receiveShadow geometry={nodes.frame.geometry} material={materials.gloss} position={[-0.21, 0.01, -2.1]} rotation={[0, 0, -Math.PI / 2]} scale={0.396} />
      <group position={[-0.21, 0.5, -2.1]} scale={0.445}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder006.geometry} material={materials['TV - Plastic Rough']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder006_1.geometry} material={materials['TV - Screen']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder006_2.geometry} material={materials['TV - Metal Brushed']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder006_3.geometry} material={materials['TV - Goldy']} />
      </group>
    </group>
  )
}

useGLTF.preload('models/TV-transformed.glb')
